rust-mcp-stack/rust-mcp-schema

.cargo/config.toml
.gitignore
src/generated_schema/2024_11_05/schema_utils.rs
tarpaulin.toml
tests/common/sample_mcp_messages.json
tests/test_deserialize.rs
tests/test_serialize.rs

Added more unit tests for the schema_utils, increasing the test coverage to 64%
- Added a cargo alias for test coverage : `cargo coverage`
- Added `tarpaulin.toml` to produce test coverage for all versions of the schema (latest , draft)
- Added more test cases to improve the test coverage of the schema_utils
1- run `cargo coverage`
2- open `.coverage/tarpaulin-report.html` after it is generated

test: test coverage for schema_utils has been increased to 64%.

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Generated `mcp_schema.rs` and `schema_utils.rs` once again, added back a test case that was removed accidentally 
- Generated mcp_schema.rs and schema_utils.rs.
- Added back the unit test for testing the default case in the detect_message_type() function

fix: generated schema and schema_utils with new test case

---

README.md
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Improved both `mcp_schema` and `schema-utils` by implementing new Traits
- Implemented the Display trait for the Result type in mcp_schema to simplify instantiation.
- Implemented `Display` trait for `ClientMessage` and `ServerMessage` variants of the `schema_utils

feat: enhance `schema_utils` and `mcp_schema`

---

scripts/run_test.sh

Added `cargo test --doc` to run Doctests, as Doctests are currently not supported in by nextest-rs.
- Added Doctest to the test script [scripts/run_test.sh](https://github.com/rust-mcp-stack/rust-mcp-schema/compare/chore/add-doc-test?expand=1#diff-da8753d6fc68fc35c731952d0a43707d9576d2f486188b83e38f13d309d31a98)
- run :
```
scripts/run_test.sh
```

chore: add Doctests to the test script

---

examples/mcp_client_handle_message.rs
examples/mcp_server_handle_message.rs
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

We previously used `serde_json::error::Error` as the associated type for the `FromStr` trait. It has now been updated to return a consistent error type that aligns with the MCP specification.
- The FromStr trait implementations now return JsonrpcErrorError if parsing the message fails.

feat: standardize error types to conform to JSON-RPC

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs
tests/test_serialize.rs

Added new utility functions to schema-utils to support MCP application development:
Added and implemented the `MCPMessage` trait with helpful methods, and provided implementations for `ClientMessage` and `ServerMessage`.
Implemented PartialEq, Eq, and Hash traits for requestId, enabling comparison and storage in HashMaps.
New functions provided by `MCPMessage` : 
- `message.is_request()` :    Returns true if the message is a response type
- `message.is_response()` : Returns true if the message is a request type
- `message.is_notification()` :  Returns true if the message is a notification type
- `message.is_error()` :  Returns true if the message represents an error
- `message.request_id()` :  Retrieves the request ID associated with the message, if applicable
- Introduced and implemented …

feat: implement new utility functions

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs
tests/test_serialize.rs

Resolved an issue where our custom serializer failed to skip optional parameters with a `None` value, resulting in invalid JSON with null that was rejected by MCP schema validation.
- Updated Serialize trait implementations to skip serializing `Option` params with `None` value

fix: serializations to skip None Params

---

scripts/run_test.sh
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs
tests/test_deserialize.rs

- Added jsonrpc() method to the `RPCMessage` trait
- Made `jsonrpc` field private in `schema_utils`
- Fixed test script to check exit code o both nextext ad doctest

fix: made jsonrpc field private, fix test script

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Introduced a new trait named `FromMessage`, this is useful for transforming mcp messages into another Type that could be serialized into a JsonrpcMessage.
For example, a `ServerMessage` can be constructed from a `rust_mcp_schema::PingRequest` by attaching a `RequestId`.
Eventually, the `ServerMessage` can be serialized into a valid `JsonrpcMessage` for transmission over the transport.
```rs
async fn send_ping_request(ping_request: rust_mcp_schema::PingRequest){
let request_id = get_next_id();
// construct a ServerMessage from the ping_request , with request_id
let message = ServerMessage::from_message(
MessageFromServer::RequestFromServer(ping_request.into()),
request_id,
).unwrap();
// serialize message into a valid rpcJsonrpcMessage string
let rpc_message_json_str = message.to_string(); …
```

feat: introduce FromMessage trait

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Several new utility functions have been added to simplify the conversion between different types, reducing boilerplate and minimizing the code required to construct various types and structures.
- Functions to extract the underlying message from `ClientMessage` and `ServerMessage`:
- `as_response()` 
-  `as_request()`
- `as_notification()`
- `as_error()`
- Implemented the `TryFrom` trait for various types to simplify the construction of :
- `ClientRequest`
- `ClientNotification`
- `ClientResult`
- `ServerRequest`
- `ServerNotification`
- `ServerResult`.

feat: add utility functions for simplified type conversions

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Implemented the `TryFrom` trait for all MCP message variants to simplify type conversions when needed.

feat: new try_from functions for all standard mcp message variants

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Implemented the `From` trait for various type variants to simplify the conversion of different types into `MessageFromClient` and `MessageFromServer`.

feat: more type conversion utilities for MessageFromServer and MessageFromClient

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Added `SdkErrorCodes` to `schema_utils`, including `ConnectionClosed` and `RequestTimeout`, along with the necessary error-related trait implementations and utility functions for creating and converting SDK errors.

feat: add SdkError codes and types

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Introduces a new error type in `schema_utils` that simplifies development by allowing any type of error to be returned in response to a `CallToolRequest` when the tool does not exist or fails for any reason.

feat: introduce CallToolError

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Added new utility functions for creating and converting types related to `CallToolResult` calls. These functions simplify the process of creating `CallToolResult` instances or returning errors when a `CallToolRequest` fails.
Usage example:
- Return a Unknown Tool Error
```rust
async fn handle_call_tool_request(
&self,
request: CallToolRequest,
) -> Result<CallToolResult, CallToolError> {
////............
return Err(CallToolError::unknown_tool(tool_name)),
}
```
- Return a `CallToolResult` with `TextContent` :
```rust
async fn handle_call_tool_request(
&self,
request: CallToolRequest,
) -> Result<CallToolResult, CallToolError> {
////............
return Ok(CallToolResult::text_content(
format!( "Successfully created directory {}", path),
None,
));
}
```

feat: new cunstructor and conversion utilities for call tool operations

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

After deprecating `get_method()` and introducing `method()` to retrieve the RPC message method, some methods remained private and were inaccessible. This PR resolves that issue.

fix: method access modifiers

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

The `MCPMessage` trait offers useful methods for messages, such as i`s_response()`,`is_request()`, `is_notification()`, `is_error()`, and `message_type()`.
However, the implementation of `MCPMessage` was missing for one of the eligible types, `MessageFromClient`, which created challenges when developing an MCP Client.
This PR adds the missing implementation for `MessageFromClient`.

fix: add missing MCPMessage trait implementation for MessageFromClient

---

.cargo/config.toml
scripts/run_clippy.sh
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs
tests/test_deserialize.rs
tests/test_serialize.rs

The deserialize implementation for `ResultFromServer` was inconsistent with `ResultFromClient`, leading to ping results from various MCP servers being deserialized into a `CustomResult` instead of a `ServerResult`.
This issue arose because `rust_mcp_schema::Result` overlaps with `CustomResult`, as both can accept arbitrary attributes.
The deserialize implementation has been updated to correctly return the appropriate type. However, `CustomResult` will be deprecated in favor of `rust_mcp_schema::Result` to eliminate this conflict.

fix: custom result deserialization conflic with rust_mcp_schema::Result

---

README.md

Tagged the crate versions specified in the README file with `x-release-please-start-version` and `x-release-please-end` to ensure they are automatically updated after each release.

chore: tag versions in readme for update with release please

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

re-generated schema files, and fixed a couple of typos in the comments

chore: re-generated schema, fixed some comment typos

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Added a new handy function to get the tool name from the `CallToolRequest` object:
```rust
async fn handle_call_tool_request( &self, request: CallToolRequest)->CallToolResult{
if request.tool_name() == SayHelloTool::tool_name() {
CallToolResult::text_content( "Hello World!".to_string(), None )
}
}
```

feat: add tool_name() method to CallToolRequest

---

LICENSE
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs

Soft deprecate `CustomResult` variants to avoid triggering warnings while maintaining compatibility without a breaking change.
- Soft deprecate `ResultFromClient::CustomResult` variants to avoid triggering warnings while maintaining compatibility without a breaking change.
- Soft deprecate `ResultFromServer::CustomResult` variants to avoid triggering warnings while maintaining compatibility without a breaking change.
- Generated latest version of schema
- updated a typo in LICENSE file

fix: soft depricate CustomResult variants to supress warnings without breaking change

---

examples/mcp_client_handle_message.rs
examples/mcp_server_handle_message.rs
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/2025_03_26/mcp_schema.rs
src/generated_schema/2025_03_26/schema_utils.rs
tests/test_serialize.rs

Replace the deprecated auto-generated struct name `JsonrpcErrorError` with a more user-friendly name : `RpcError`
- introduced a more friendly name for auto-generated name `JsonrpcErrorError`, this is not a breaking change, but it is recommended to use `RpcError` instead.
- Updated tests and schema_utils to use new struct name

refactor: deprecated auto-generated struct name JsonrpcErrorError

---

examples/mcp_client_handle_message.rs
src/generated_schema.rs
src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/2025_03_26/mcp_schema.rs
src/generated_schema/2025_03_26/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs
src/generated_schema/protocol_version.rs
tests/test_serialize.rs

Added ProtocolVersion enum, and updated draft version to the latest.
- Add new `ProtocolVersion` enum
- Updated crate to the latest draft version changes

feat: add protocol version enum, update draft version

---

Cargo.toml
README.md
examples/mcp_client_handle_message.rs
examples/mcp_server_handle_message.rs
scripts/run_test.sh
src/generated_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/draft/schema_utils.rs
src/rust-mcp-schema.rs
tests/2024_11_05_exclusive.rs
tests/common/common.rs
tests/miscellaneous.rs
tests/test_deserialize.rs
tests/test_serialize.rs

This PR introduces support for enabling multiple MCP Protocol schema versions concurrently. While one version is designated as the default, additional versions can be activated via feature flags and accessed through clearly named modules.
- Introduced versioned internal module names to avoid conflicts
- Non-default schemas are now accessible via modules such as:
- `rust_mcp_schema::mcp_2024_11_05`
- `rust_mcp_schema::mcp_draft`
- The default schema version remains enabled by default.

feat!: add support for multiple active schema versions 

---

src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/2025_03_26/schema_utils.rs
src/generated_schema/2025_06_18/schema_utils.rs
src/generated_schema/draft/schema_utils.rs

safety.
Updated `invalid_arguments()` function argument types to improve flexibility and type safety

chore: update function argument types to improve flexibility and type

---

src/generated_schema/2024_11_05/mcp_schema.rs
src/generated_schema/2024_11_05/schema_utils.rs
src/generated_schema/2025_03_26/mcp_schema.rs
src/generated_schema/2025_03_26/schema_utils.rs
src/generated_schema/2025_06_18/mcp_schema.rs
src/generated_schema/2025_06_18/schema_utils.rs
src/generated_schema/draft/mcp_schema.rs
src/generated_schema/draft/schema_utils.rs
src/rust-mcp-schema.rs
tests/test_serialize.rs

Introduced new utility functions to help with `mcp_elicit` macro development and auto generating PrimitiveSchemaDefinition from serde Mapped values
- implemented TryFrom trait for PrimitiveSchemaDefinition to help `mcp_elicit` macro development  for auto generating ElicitRequestedSchema.
- renamed ElicitRequestParamsRequestedSchema to ElicitRequestedSchema
and deprecated ElicitRequestParamsRequestedSchema

feat: elicit helper methods

---

src/generated_schema/2025_06_18/mcp_schema.rs
src/generated_schema/2025_06_18/schema_utils.rs

**Closes:** #75
As identified in issue #75, the individual `*Request` structs (e.g., `PingRequest`, `ListResourcesRequest`) do not currently validate that their `method` field matches the constant value defined in the JSON schema. This creates ambiguity. For example, a JSON payload like:
```json
{
"method": "wrong/method",
"params": { /* ... valid params for ListResourcesRequest ... */ }
}
```
could be incorrectly deserialized as a `ListResourcesRequest`. The deserialization process should fail fast if the `method` name is incorrect for the target struct.
This pull request proposes a robust pattern to validate the `method` field by leveraging Serde's `#[serde(deserialize_with = "...")]`:
1.  Deserializes the incoming value as a string.
2.  Compares it against the expected constant value …

feat: support validation for method fields in `*Request`
